### ISSUE TITLE
Opting out of the feedback popover

### ISSUE THREAD

**Issue by mriehl** [ImmobilienScout24/afp-web#2]
I use [vimperator](http://www.vimperator.org/vimperator) and have many accounts in the afp-web main page.

So starting out with focus on the account search field lets me jump into my console with 4 keystrokes. But the feedback popover is showing up every time for me (I clear cookies, localStorage and history upon browser quit), so the search field doesn't have focus and I have to grab the mouse to get rid of the popover.

It would be great if there was a way to opt out of the popover statically (e.G. query param). As an alternative maybe it would be acceptable to close the popover if the escape key is pressed.

What do you think?

**Comment by esc** [comment]
I think it would be about time to disable the feedback again, have we not collected enough data?

**Comment by mriehl** [comment]
For now I have an adblock rule which solves my problem.

**Comment by schlomo** [comment]
Thanks for your feedback.

In the case that we will put another NPS into the web UI then we will implement it so that it will ask every user only once.
